import { Record } from "@bonfida/spl-name-service";

export const recordsToFetch = [
  Record.IPFS,
  Record.ARWV,
  Record.SOL,
  Record.ETH,
  Record.BTC,
  Record.LTC,
  Record.DOGE,
  Record.Email,
  Record.Url,
  Record.Discord,
  Record.Github,
  Record.Reddit,
  Record.Twitter,
  Record.Telegram,
  Record.Pic,
  Record.SHDW,
  Record.POINT,
  Record.Injective,
  Record.BSC,
  Record.Backpack,
  Record.TXT,
];
